const api = {
  // auth.login
  getToken: '/login/token',
  getUserInfo: '/login/user_info',
  // auth.permission
  getPermissionList: '/permission',
  activatePermission: '/permission/activate',
  removePermission: '/permission/remove',
  // auth.role
  getRoleList: '/role',
  updateRoleInfo: '/role/info',
  saveRoleInfo: '/role',
  activateRole: '/role/activate',
  removeRole: '/role/remove',
  // auth.user
  getUserList: '/user',
  updateUserInfo: '/user/info',
  saveUserInfo: '/user',
  activateUser: '/user/activate',
  removeUser: '/user/remove',
  // asset.host
  getHostList: '/host',
  getHostService: '/host/service',
  updateHostInfo: '/host/info',
  saveHostInfo: '/host',
  activateHost: '/host/activate',
  removeHost: '/host/remove',
  // asset.domain
  getDomainList: '/domain',
  updateDomainInfo: '/domain/info',
  saveDomainInfo: '/domain',
  activateDomain: '/domain/activate',
  removeDomain: '/domain/remove',
  // asset.service
  getServiceList: '/service',
  // asset.http
  getHTTPList: '/http',
  updateHTTPInfo: '/http/info',
  saveHTTPInfo: '/http',
  activateHTTP: '/http/activate',
  removeHTTP: '/http/remove',
  // asset.cgi
  getCGIList: '/cgi',
  updateCGIInfo: '/cgi/info',
  saveCGIInfo: '/cgi',
  activateCGI: '/cgi/activate',
  removeCGI: '/cgi/remove',
  // asset.zone
  getZoneList: '/zone',
  updateZoneInfo: '/zone/info',
  saveZoneInfo: '/zone',
  removeZone: '/zone/remove',
  // scanner.plugin
  getPluginList: '/plugin',
  updatePluginInfo: '/plugin/info',
  savePluginInfo: '/plugin',
  activatePlugin: '/plugin/activate',
  removePlugin: '/plugin/remove',
  // scanner.task
  getTaskList: '/task',
  updateTaskInfo: '/task/info',
  saveTaskInfo: '/task',
  activateTask: '/task/activate',
  removeTask: '/task/remove',
  enableTask: '/task/enable',
  disableTask: '/task/disable'
}

export default api
