FROM python:3.6

RUN useradd -d /home/flask -m -s /bin/bash flask -p flask
WORKDIR /home/flask
USER flask

COPY requirements.txt requirements.txt
RUN python -m venv venv
RUN venv/bin/pip install -r requirements.txt
RUN venv/bin/pip install gunicorn gevent

COPY app app
COPY workers workers
COPY wsgi.py config.py celery_worker.py .flaskenv ./
COPY docker/boot_app.sh ./

# run-time configuration
EXPOSE 8080
ENTRYPOINT ["./boot_app.sh"]