FROM python:3.6

RUN apt-get update
RUN apt-get install -y nmap

COPY requirements.txt requirements.txt
RUN python -m venv venv
RUN venv/bin/pip install -r requirements.txt

COPY app app
COPY workers workers
COPY wsgi.py config.py celery_worker.py .flaskenv ./
COPY docker/boot_celery_port_monitor.sh ./

# run-time configuration
ENTRYPOINT ["./boot_celery_port_monitor.sh"]