"""add Task options

Revision ID: 0b7cadf516d4
Revises: c76cf6b601e8
Create Date: 2018-09-25 12:11:07.400990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b7cadf516d4'
down_revision = 'c76cf6b601e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('options', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'options')
    # ### end Alembic commands ###
